// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP4fvSUcYxuy3V_hQHNlgzp7Z3hXU2mX8',
    appId: '1:271803465023:web:c2a11a5f44361ce874678a',
    messagingSenderId: '271803465023',
    projectId: 'chat-app-th-2ba6d',
    authDomain: 'chat-app-th-2ba6d.firebaseapp.com',
    storageBucket: 'chat-app-th-2ba6d.appspot.com',
    measurementId: 'G-43DRXG8E2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZg2XuQS0vkggpbloStl6oag4afAY5w7I',
    appId: '1:271803465023:android:d2a6f30fec23d6bc74678a',
    messagingSenderId: '271803465023',
    projectId: 'chat-app-th-2ba6d',
    storageBucket: 'chat-app-th-2ba6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFODmPnbwrHQ5vuSPYjuSGZ3_qLOMfcNw',
    appId: '1:271803465023:ios:192e81fef8387d0274678a',
    messagingSenderId: '271803465023',
    projectId: 'chat-app-th-2ba6d',
    storageBucket: 'chat-app-th-2ba6d.appspot.com',
    iosBundleId: 'com.example.chatAppTh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFODmPnbwrHQ5vuSPYjuSGZ3_qLOMfcNw',
    appId: '1:271803465023:ios:64f3c619219c62fa74678a',
    messagingSenderId: '271803465023',
    projectId: 'chat-app-th-2ba6d',
    storageBucket: 'chat-app-th-2ba6d.appspot.com',
    iosBundleId: 'com.example.chatAppTh.RunnerTests',
  );
}
